// AUTO-GENERATED by `stellar scaffold` — do not edit.
// Regenerated on every build/redeploy from your deployed contracts.
// To customize a client, import it into your own code under app/ instead.

import { network } from "@stellar-scaffold/app-lib"
import { Client as Vault } from "vault"
import { Client as Counter } from "counter"

const { passphrase: networkPassphrase, rpcUrl, id } = network

const options = {
	networkPassphrase,
	rpcUrl,
	allowHttp: id === "local",
	publicKey: undefined,
}

export const vault = new Vault({
	...options,
	contractId: "CARQ5UVSDA2ERYX3TDBLGYAPLOWTOQCMC5TVE6YID7JMLR2PVKKFUW4J",
})

export const counter = new Counter({
	...options,
	contractId: "CALK7NDPPIKT5DTHNFOZTXLJQWSNHWPFH4NIOX2D64CUOCT5UGTQWMAY",
})
