// These ids are testnet-pinned; a mainnet target would need a network-keyed lookup.
export const ADMIN_VAULT_CONTRACT_ID =
	"CAHC7K5NWSN3VFKBWU7VJT7H3E4VF55ODD6ZMRB32MCII64G3YAMI5QA"

export const ADMIN_ACCOUNT =
	"GDVL4VKURSZ7R66IWAORMUNHYHHDQ5Y65TMPWIGV6WDVKTRZZLQBYNXQ"
