// These ids are testnet-pinned; a mainnet target would need a network-keyed lookup.
export const ADMIN_VAULT_CONTRACT_ID =
	"CD5RPBZ6JK5RHJD2JFXCGKFSD7X7HSXCZGE7NNJLOEANPJQQHS57JTGK"

export const ADMIN_ACCOUNT =
	"GDVL4VKURSZ7R66IWAORMUNHYHHDQ5Y65TMPWIGV6WDVKTRZZLQBYNXQ"
